apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/bancobasa/basa-n8n-platform.git'
    path: 'apps/n8n'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
